### ISSUE TITLE
question: email validation

### ISSUE THREAD

**Issue by hanssnabilie** [EtherPOS/single-page-login#12]
hello Steeve,

I was wondering how you're doing the email validation. Can you tell me how to do this best without changing the source code? Perhaps I'm overlooking something obvious or is this on the road map still.

**Comment by stephentcannon** [comment]
I am not doing any email validation.  

I am not convinced it should be part of this package but it might be.

You could do that on your own in an Accounts.onCreateUser

See this for more details: http://docs.meteor.com/#/full/accounts_oncreateuser

Maybe with some code like this

````
var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\  ".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA  -Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    if(!re.test(email)){
      if(name){
        throw name.replace(/_/g, ' ') + ' must be a valid email address.';
      } else {
        throw 'Please enter a valid <b>email</b> address.';
      }
    }
````

This does have me thinking whether this should be baked in.  I am not sure if email validation is baked into Meteor.

**Comment by hanssnabilie** [comment]
Thank you Steeve, 

I am just looking at it from a usability point of view, for the user this really has to be implemented. The oncreateuser is a server function and I would like to see a check clientside. The code for this is currently inside your package. 

So I guess my real question is; how can I change the package, overrule the keydown event in the input or change the google image for example. Should I see your package as a start point and just use the files or are you planning to expand and parametrize it?

**Comment by stephentcannon** [comment]
I would suggest looking through the package code.

You are welcome to submit a PR for things like overriding the google image or adding client side email address checking.
